# Windows
# Dynamic library
# Release only
# Environment passthrough for VCPKG_TOKEN
# Pass VCPKG_Python3_EXECUTABLE

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_ENV_PASSTHROUGH_UNTRACKED VCPKG_TOKEN)
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED VCPKG_Python3_EXECUTABLE)
if(DEFINED ENV{VCPKG_Python3_EXECUTABLE})
  set(VCPKG_HASH_ADDITIONAL_FILES "$ENV{VCPKG_Python3_EXECUTABLE}")
endif()
