set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_BUILD_TYPE release)

set(VCPKG_FIXUP_ELF_RPATH ON)

set(VCPKG_LINKER_FLAGS "-static-libgcc -static-libstdc++")

set(VCPKG_ENV_PASSTHROUGH VCPKG_Python3_EXECUTABLE)
